service: theodo-link

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

custom:
  stage: ${opt:stage, self:provider.stage}
  stageConfig: ${file(./config.yml):${self:custom.stage}}
  webpack:
    packager: "yarn"
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: ${self:custom.stageConfig.domainName}
    basePath: ""
    stage: ${self:custom.stage}
    createRoute53Record: true
  appSync:
    name: ${self:service}-${self:custom.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: ${self:custom.stageConfig.userPoolId}
    mappingTemplates:
      - dataSource: Links
        type: Mutation
        field: createLink
        request: "createLink-request.vtl"
        response: "createLink-response.vtl"
      - dataSource: Links
        type: Mutation
        field: updateLink
        request: "updateLink-request.vtl"
        response: "updateLink-response.vtl"
      - dataSource: Links
        type: Mutation
        field: deleteLink
        request: "deleteLink-request.vtl"
        response: "deleteLink-response.vtl"
      - dataSource: Links
        type: Query
        field: listLinks
        request: "listLinks-request.vtl"
        response: "listLinks-response.vtl"
      - dataSource: Links
        type: Query
        field: getLink
        request: "getLink-request.vtl"
        response: "getLink-response.vtl"
    schema: schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Links
        description: Theodo Links Table
        config:
          tableName: { Ref: LinksDynamoDbTable }

functions:
  link:
    handler: src/link.handler
    events:
      - http:
          path: "/{link+}"
          method: get

resources:
  Resources:
    LinksDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
